language: go
env:
  - GO111MODULE=on
go:
  - 1.11.x
services:
  - docker


jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t $DOCKER_USERNAME/go-apps:go-helloworld .
      - docker images
    - stage: test
      script:
      - docker run -d -p 80:8080 --name  go-helloworld $DOCKER_USERNAME/go-apps:go-helloworld
      - docker exec -it go-helloworld /bin/sh -c "cd tests; go test"
    - stage: deploy
      script:
      - docker push $DOCKER_USERNAME/go-apps:go-helloworld