language: go
env:
  - GO111MODULE=on
go:
  - 1.11.x
services:
- docker
before_install:
- docker build -t "$DOCKER_USERNAME"/go-apps:go-helloworld .
- docker run -d -p 80:8080 --name  go-helloworld "$DOCKER_USERNAME"/go-apps:go-helloworld
test:
- docker exec -it go-helloworld /bin/sh -c "cd server/tests; go test"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: dev